namespace: gitrgoliveira
name: vault
version: 0.0.1
description: HashiCorp Vault Enterprise Event-Driven Automation plugin for agentless rotation of Vault secrets, using real-time event monitoring via WebSocket
readme: README.md
repository: https://github.com/gitrgoliveira/vault-ansible-eda
homepage: https://github.com/gitrgoliveira/vault-ansible-eda
documentation: https://github.com/gitrgoliveira/vault-ansible-eda/blob/main/README.md
issues: https://github.com/gitrgoliveira/vault-ansible-eda/issues
authors:
  - Ricardo Oliveira <ricardo@example.com>
license:
  - MPL-2.0
tags:
  - vault
  - hashicorp
  - event_driven_automation
  - eda
  - websocket
  - monitoring
  - security
  - kv
dependencies: {}