name: Test Collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible-core>=2.14 websockets>=10.0
        
    - name: Validate collection structure
      run: |
        cd collections/ansible_collections/gitrgoliveira/vault
        ansible-galaxy collection build --verbose --force
        
    - name: Install collection locally
      run: |
        cd collections/ansible_collections/gitrgoliveira/vault
        COLLECTION_FILE=$(ls gitrgoliveira-vault-*.tar.gz)
        ansible-galaxy collection install $COLLECTION_FILE --force
        
    - name: Test collection import
      run: |
        python -c "
        import sys
        sys.path.append('/home/runner/.ansible/collections/ansible_collections')
        try:
            from gitrgoliveira.vault.plugins.event_source.vault_events import main
            print('✓ Collection plugin imports successfully')
        except ImportError as e:
            print('✗ Collection plugin import failed:', e)
            sys.exit(1)
        "
        
    - name: Validate galaxy.yml
      run: |
        cd collections/ansible_collections/gitrgoliveira/vault
        python -c "
        import yaml
        with open('galaxy.yml') as f:
            data = yaml.safe_load(f)
        
        required_fields = ['namespace', 'name', 'version', 'description', 'authors']
        for field in required_fields:
            if field not in data:
                print(f'✗ Missing required field: {field}')
                exit(1)
            print(f'✓ {field}: {data[field]}')
        
        print('✓ galaxy.yml validation passed')
        "